on:
  issue_comment:
    types: [created]
name: Invite a new collaborator

jobs:
  build:
    name: Invite contributor to the Org
    runs-on: ubuntu-latest     
    steps:
    - uses: actions/checkout@master
    - name: Invite collaborator based on a comment
      uses: bdougie/invite-based-on-comment@v2.1.1
      env:
        GITHUB_TOKEN: ${{ secrets.BDOUGIE_TOKEN }}
        TEAM_ID: 123456
        ORG: 'github-craftwork'
