name: Inclusive Organization
on:
  push:
    branches: master
jobs:
  invite:
    runs-on: ubuntu-latest
    steps:
      - name: Invite contributor to the organization
        uses: lekterable/inclusive-organization-action@v1.1.0
        with:
          organization: dscpccoe
          comment: Congrats on your first PR 🎉 \n\n Invitation for joining the DSC PCCoE GitHub Organization has been sent to you. \nWelcoome to the community!
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
